# Hello Numpy

Introduction to NUMPY
By Igor Janos


In [1]:
import numpy as np


## List vs. Numpy Array

List (zoznam) je datova struktura jazyka Python.

Numpy array je N-rozmerny tenzor. Moze to byt vektor, matica, alebo tenzor vyssieho stupna. Prvky tenzora maju rovnaky typ.

List je mozne skonvertovat na Numpy array.

In [2]:
# This is a simple list
listItems = [1, 2, 3, 4, 5]
print('List contains {} items: {}'.format(len(listItems), listItems))


List contains 5 items: [1, 2, 3, 4, 5]


In [3]:
# List can also contain elements of different types
listItems2 = [0, 1.0, True, 'StringItem', {"x": "1.0"} ]
print(listItems2)


[0, 1.0, True, 'StringItem', {'x': '1.0'}]


Skusime spravit maticu M pomocou zoznamu - su to vlastne dva vnorene zoznamy.

In [4]:
M = [[1,2,3], [4,5,6], [7,8,9]]
print(M)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Tazko je nejak presne vyjadrit rozmery takejto matice. Kazdy vnoreny zoznam moze mat roznu velkost....

### <b>Zoznam nie je vhodna datova struktura na pracu s maticami !</b>

## Numpy Arrays


In [5]:
# Spravime numpy array - vyzera ako zoznam
a = np.array([1, 2, 3, 4])
print('Numpy array: ', a)
print('Element type: ', a.dtype)
print('Shape: ', a.shape)


Numpy array:  [1 2 3 4]
Element type:  int64
Shape:  (4,)


Shape: (4,) = RANK 1 


In [6]:
# Skusime spravit maticu
m = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=float)
print('Numpy array: \n', m)
print('Element type: ', m.dtype)
print('Shape: ', m.shape)


Numpy array: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Element type:  float64
Shape:  (3, 3)


Shape: (3, 3) = RANK 2       Dvojrozmerna matica.

Vsetky vypocty, ktore budeme robit v tychto ukazkach, sa budu tykat RANK 2 arrayov.
RANK 1 je nieco, comu sa budeme chciet vyhnut.

Aj vektory - stlpcove alebo riadkove - budeme pouzivat ako RANK 2 arraye.


In [7]:
# Skusime spravit riadkovy vektor
v = np.array([[1, 2, 3, 4]], dtype=float)
print('Shape: ', v.shape)
print(v)
print('')

# Spravime z neho Transponovany - stlpcovy vektor
v = v.T
print('Transposed shape: ', v.shape)
print(v)


Shape:  (1, 4)
[[1. 2. 3. 4.]]

Transposed shape:  (4, 1)
[[1.]
 [2.]
 [3.]
 [4.]]


## Rez maticou

Rez znizuje Rank !

In [8]:
# Spravime 3x3 maticu
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m)
print('Shape: ',m.shape)   # >> (3, 3)
print('')


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)



In [9]:
# Druhy riadok

r = m[1,:]    # >> (3, ) Rank 1
print('Druhy riadok - Rank 1:')
print(r)
print(r.shape)
print('')

r = m[1,None]   # >> (1, 3) Rank 2
print('Druhy riadok - Rank 2:')
print(r)
print(r.shape)
print('')


Druhy riadok - Rank 1:
[4 5 6]
(3,)

Druhy riadok - Rank 2:
[[4 5 6]]
(1, 3)



In [10]:
# Druhy stlpec

c = m[:,1]    # >> (3, ) Rank 1
print('Druhy stlpec - Rank 1:')
print(c)
print(c.shape)
print('')

c = m[:,1,None]   # >> (3, 1) Rank 2
print('Druhy stlpec - Rank 2:')
print(c)
print(c.shape)


Druhy stlpec - Rank 1:
[2 5 8]
(3,)

Druhy stlpec - Rank 2:
[[2]
 [5]
 [8]]
(3, 1)


## Broadcasting

Ak sa snazime vykonavat maticovu operaciu nad operandami s nevyhovujucim tvarom, vie si Numpy pomoct zmysluplnym duplikovanim hodnot.

In [11]:
# Spravime maticu M - 2x2, a skalar b
M = np.array([[1,2], [3,4]])     # >> (2, 2)
b = 1

print('Matrix M: \n', M, '\n')
print('b: \n', b, '\n')
print('Matrix M+b: \n', M+b, '\n')


Matrix M: 
 [[1 2]
 [3 4]] 

b: 
 1 

Matrix M+b: 
 [[2 3]
 [4 5]] 



In [12]:
# Spravime riadkovy vektor c - 1x2
c = np.array([[5, 5]])           # >> (1, 2)

print('Matrix M: \n', M, '\n')
print('c: \n', c, '\n')
print('Matrix M+c: \n', M+c, '\n')

Matrix M: 
 [[1 2]
 [3 4]] 

c: 
 [[5 5]] 

Matrix M+c: 
 [[6 7]
 [8 9]] 



In [13]:
# Spravime stlpcovy vektor d - 2x1
d = np.array([[10], [10]])  # >> (2, 1)

print('Matrix M: \n', M, '\n')
print('d: \n', d, '\n')
print('Matrix M+d: \n', M+d, '\n')


Matrix M: 
 [[1 2]
 [3 4]] 

d: 
 [[10]
 [10]] 

Matrix M+d: 
 [[11 12]
 [13 14]] 



## Funkcie nad Numpy arrayom

Kniznica Numpy vie vykonavat matematicke funkcie nad elementami matic. Napriklad exp.

In [14]:
import math


In [15]:
# Volame tradicnu math.exp funkciu
a = -1.0
print(math.exp(a))


0.36787944117144233


In [16]:
# Volame numpy.exp funkciu
a = np.array([[-1.0, 0, 1.0]], dtype=float)
r = np.exp(a)

print('a: \n', a, '\n')
print('r: \n', r, '\n')


a: 
 [[-1.  0.  1.]] 

r: 
 [[0.36787944 1.         2.71828183]] 



In [17]:
# Boolean arraye
a = np.arange(start=0, stop=10, step=1, dtype=int)
print('a: \n', a, '\n')

# Element-wise porovnanie
b = (a > 5)
print('b: \n', b, '\n')


a: 
 [0 1 2 3 4 5 6 7 8 9] 

b: 
 [False False False False False False  True  True  True  True] 



## Inicializacie

Matice mozeme inicializovat bud na konkretnu hodnotu - 0, 1.
Alebo nahodne z rozdelenia (uniform, normal, ... )

In [18]:
# Inicializujeme vsetky elementy na hodnotu 1
v = np.ones(shape=(5, 10), dtype=float)
print(v)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [19]:
# Inicializujeme vsetky elementy na hodnotu 0
v = np.zeros(shape=(5, 10), dtype=float)
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [20]:
# Inicializovat s rovnakym tvarom
v2 = np.ones_like(v)
print(v2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [21]:
# Inicializacia nahodnymi hodnotami - Uniform Distribution
v = np.random.rand(2, 3)    # <0; 1>
print(v)
print(v.shape)

[[0.7541334  0.30682289 0.58500078]
 [0.84556886 0.49526813 0.00113118]]
(2, 3)


In [22]:
# Inicializacia nahodnymi hodnotami - Normal Distribution
v = np.random.randn(2, 3)   # Normal(mean=0, stddev=1)
print(v)
print(v.shape)

[[ 0.01010036  0.57323748  0.44481306]
 [-0.96359239 -0.41406268 -1.46058569]]
(2, 3)
